# Generated by Django 3.2.5 on 2021-07-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='main_projects_for_participant',
            field=models.ManyToManyField(to='main.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_picture',
            field=models.ImageField(upload_to='', verbose_name='Картинка проекта'),
        ),
    ]
