# Generated by Django 3.2.5 on 2021-07-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210713_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='avatar',
            field=models.ImageField(upload_to='', verbose_name='Картинка проекта'),
        ),
    ]
