# Generated by Django 3.2.5 on 2021-07-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210713_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_picture',
            field=models.ImageField(max_length=255, upload_to='', verbose_name='Картинка проекта'),
        ),
    ]
