# Generated by Django 3.2.5 on 2021-07-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_project_project_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='avatar',
            field=models.ImageField(max_length=255, upload_to='', verbose_name='Картинка Участника'),
        ),
    ]
