# Generated by Django 3.2.5 on 2021-07-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_participant_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='avatar',
            field=models.ImageField(max_length=500, upload_to='', verbose_name='Картинка Участника'),
        ),
    ]
