# Generated by Django 3.2.5 on 2021-07-22 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210715_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chronicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.TextField(verbose_name='Имя проекта')),
            ],
        ),
        migrations.CreateModel(
            name='Entry_for_chronicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название записи')),
                ('description', models.TextField(verbose_name='Описание')),
                ('attachments', models.JSONField(verbose_name='Вложения')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('date_of_action', models.DateField()),
                ('chronicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chronicle')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='chronicle_for_project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chronicle'),
        ),
    ]
