# Generated by Django 3.2.5 on 2021-07-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_for_chronicle',
            name='attachments',
            field=models.FileField(null=True, upload_to='', verbose_name='Вложения'),
        ),
        migrations.AlterField(
            model_name='project',
            name='qr_token',
            field=models.CharField(max_length=96, verbose_name='QR токен для проекта'),
        ),
    ]
