# Generated by Django 3.2.5 on 2021-07-27 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210727_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='chronicle_for_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chronicle'),
        ),
    ]
