# Generated by Django 3.2.5 on 2021-07-27 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_project_chronicle_for_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='id_chronicle',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='chronicle_for_project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.chronicle'),
        ),
    ]
